In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
# dd=pd.read_csv('data375k.csv')
# insample, remainder = train_test_split(dd, test_size=10000,  random_state=115)

# insample_small = insample.head(1000)

In [17]:
insample

,MarginPrice,LookId,SellerName,HedgeAdvisorName,AbaMemberBit,CommitPeriodGrp,LoanAmt,BaseLoanAmt,NoteRate,PropTypeName,...,TotalDebtExpenseRatio,TotalMonthlyVerifiedIncomeAmt,UnknownTotalMonthlyVerifiedIncomeAmtBit,BenchMarginPrice,WinBoundaryMarginPrice,LossBoundaryMarginPrice,WinAboveObjectiveWt,WinBelowObjectiveWt,LossAboveObjectiveWt,LossBelowObjectiveWt
328065,0.136,891299,leaderone,resi,0,7,216000.0,216000.0,6.375,singlefamily,...,34.00,5508.53000,0,-0.0529,NaN,0.136,0,1,1,0.02
368288,0.142,1140510,churchillmortgage,other,0,7,208000.0,208000.0,6.750,condo,...,32.20,5936.83000,0,-0.0964,NaN,0.142,0,1,1,0.02
216162,0.590,110218,guaranteedrate,other,0,7,147250.0,147250.0,6.775,singlefamily,...,34.33,6899.20000,0,-0.0113,NaN,0.590,0,1,1,0.02
370077,0.140,1148071,amerisave,compass,0,10,505697.0,497000.0,5.500,singlefamily,...,37.67,11281.64000,0,-0.1106,NaN,0.140,0,1,1,0.02
151163,0.160,45070,guaranteedrate,other,0,7,710910.0,710910.0,5.550,singlefamily,...,45.01,13665.08000,0,-0.2584,NaN,0.160,0,1,1,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79579,0.333,183042,eustismortgage,mct,0,7,340402.0,340402.0,7.125,unit2to4,...,32.60,15166.67000,0,-0.0364,NaN,0.333,0,1,1,0.02
79504,0.199,182962,leaderone,resi,0,7,397705.0,397705.0,6.500,singlefamily,...,58.43,8240.80000,0,-0.0364,NaN,0.199,0,1,1,0.02
67055,0.224,14647,nexbank,compass,1,10,332500.0,332500.0,7.250,singlefamily,...,43.02,11041.10165,1,-0.1476,NaN,0.224,0,1,1,0.02
270752,0.504,1067177,guildmortgage,mct,0,15,374900.0,374900.0,6.125,singlefamily,...,34.80,11521.00000,0,-0.0355,NaN,0.504,0,1,1,0.02
203538,1.662,198089,victorian,mct,0,7,68633.0,67453.0,7.125,singlefamily,...,20.10,3120.00000,0,-0.0954,NaN,1.662,0,1,1,0.02

In [6]:
remainder

,LookId,SellerName,HedgeAdvisorName,AbaMemberBit,CommitPeriodGrp,LoanAmt,BaseLoanAmt,NoteRate,PropTypeName,PropUsageTypeName,...,TotalDebtExpenseRatio,TotalMonthlyVerifiedIncomeAmt,UnknownTotalMonthlyVerifiedIncomeAmtBit,BenchMarginPrice,WinBoundaryMarginPrice,LossBoundaryMarginPrice,WinAboveObjectiveWt,WinBelowObjectiveWt,LossAboveObjectiveWt,LossBelowObjectiveWt
113743,1048429,baycapitalmortgage,mct,0,7,418950.0,418950.0,7.625,condo,primaryresidence,...,35.80,12707.78,0,-0.0761,NaN,0.885000,0,1,1,0.02
136682,1060099,mortgageresearch,compass,0,7,278000.0,278000.0,6.750,singlefamily,primaryresidence,...,37.16,7775.90,0,-0.0355,NaN,0.945000,0,1,1,0.02
42579,1041588,southeastmortgage,resi,0,7,156900.0,156900.0,6.375,singlefamily,primaryresidence,...,42.75,3278.49,0,-0.0596,NaN,0.505000,0,1,1,0.02
13047,1053853,southerntrust,resi,0,7,348600.0,348600.0,6.875,condo,investment,...,48.14,64428.94,0,-0.0325,-0.287875,-0.287875,0,1,1,0.00
175325,1037316,kindlending,other,0,7,335805.0,330030.0,6.250,singlefamily,primaryresidence,...,50.71,6047.41,0,-0.0704,NaN,0.950000,0,1,1,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79654,1069745,leaderone,resi,0,7,218500.0,218500.0,7.625,singlefamily,primaryresidence,...,44.57,6551.31,0,-0.0585,NaN,0.633000,0,1,1,0.02
28054,633670,paramount,compass,0,7,335068.0,329306.0,6.750,singlefamily,primaryresidence,...,27.37,14837.49,0,-0.1429,0.185000,NaN,0,1,1,0.02
8706,189729,mifinancial,mct,0,15,375000.0,375000.0,4.875,pud,primaryresidence,...,25.60,19905.90,0,-0.0638,NaN,0.160000,0,1,1,0.02
76869,200308,mutualofomahamortgageinc,compass,0,7,201465.0,201465.0,6.750,singlefamily,primaryresidence,...,34.38,10498.97,0,-0.0954,NaN,0.569000,0,1,1,0.02
50946,965680,farmingtonfinancialcapstarbank,mct,1,7,352800.0,352800.0,5.500,singlefamily,primaryresidence,...,36.70,10023.33,0,-0.0769,NaN,0.268000,0,1,1,0.02

In [18]:
insample.to_csv('insample.csv', index=False)
insample_small.to_csv('insample_small.csv', index=False)
remainder.to_csv('outofsample.csv', index=False)

In [3]:
x=pd.read_csv('shallow_wide\\hptune_shallow.csv')

In [4]:
x

,dense_start_S,layersS,dense_0S,dense_start_dM,layersM,dense_0dM,dense_start_W,layersW,units_0W,dense_1S,dense_1dM,dense_2dM,units_1W,units_2W,Score
0,235,2,200,120,3,450,485,3,145,100,100,100,100,100,0.387291
1,875,1,850,210,2,150,545,3,245,350,300,950,230,545,0.410787